# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI build and publish

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Create maven settings.xml
      uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: '[
          {"id": "github-sinha108", "username": "$GITHUB_ACTOR", "password": "${{ secrets.TKLTEST_PKGS_PAT }}"}
        ]'
    - name: Download Randoop jars
      run: mvn --batch-mode download:wget@get-randoop-jar download:wget@get-replacecall-jar
    - name: Build with Maven
      run: mvn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 --batch-mode package 

  # publish to GitHub Packages if tests pass and the workflow is running on the main branch
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Create maven settings.xml
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: '[
          {"id": "github-sinha108", "username": "$GITHUB_ACTOR", "password": "${{ secrets.TKLTEST_PKGS_PAT }}"}
        ]'
      - name: Download Randoop jars
        run: mvn --batch-mode download:wget@get-randoop-jar download:wget@get-replacecall-jar
      - name: Delete old package version
        uses: actions/delete-package-versions@v1
        with:
          package-name: 'org.konveyor.tackle-test-generator-core'
      - name: Publish to GitHub Packages
        run: mvn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 --batch-mode deploy -Dmaven.test.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
