# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: UI test generator build and publish

on:
  push:
    paths-ignore:
      - 'tackle-test-generator-unit/**'
      - '.github/workflows/unit_testgen_ci.yml'
      - 'doc/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'tackle-test-generator-unit/**'
      - '.github/workflows/unit_testgen_ci.yml'
      - 'doc/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Install prerequisites (chromedriver)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk2.0-0 chromium-chromedriver
        chromedriver --version
    - name: Create maven settings.xml
      uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: '[
          {"id": "github-sinha108", "username": "$GITHUB_ACTOR", "password": "${{ secrets.TKLTEST_PKGS_PAT }}"}
        ]'
    - name: Run crawljax config test case on sample data
      run: |
        mvn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 \
          --batch-mode test -Dtest=CrawljaxRunnerTest#testCreateCrawljaxConfigurationSample
    - name: Pull test webapps
      run: |
        git submodule init
        git submodule update
    - name: Run petclinic webapp and test case
      run: |
        cd tackle-test-generator-ui/test/data/webapps/petclinic && ./deploy_app.sh start --build && cd ../../../..
        mvn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 \
          --batch-mode test -Dtest=CrawljaxRunnerTest#testCrawljaxRunnerPetclinic
        cd test/data/webapps/petclinic && ./deploy_app.sh stop
    - name: Run addressbook webapp and test case
      run: |
        cd tackle-test-generator-ui/test/data/webapps/addressbook && ./deploy_app.sh start && cd ../../../..
        mvn -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 \
          --batch-mode test -Dtest=CrawljaxRunnerTest#testCrawljaxRunnerAddressbook
        cd test/data/webapps/addressbook && ./deploy_app.sh stop

  # publish to GitHub Packages if workflow is running on the main branch
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Create maven settings.xml
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: '[
          {"id": "github-sinha108", "username": "$GITHUB_ACTOR", "password": "${{ secrets.TKLTEST_PKGS_PAT }}"}
        ]'
      - name: Delete old package version
#        uses: actions/delete-package-versions@v2.0.1
        uses: smartsquaregmbh/delete-old-packages@v0.4.0
        with:
#          package-name: 'org.konveyor.tackle-test-generator-ui'
          names: 'org.konveyor.tackle-test-generator-ui'
          keep: 0
      - name: Publish to GitHub Packages
        run: mvn -f tackle-test-generator-ui -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 --batch-mode deploy -Dmaven.test.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
